mongodb:
  url: "mongodb+srv://pictureminer:pictureminer@cluster0.qq7vze3.mongodb.net/?retryWrites=true&w=majority"
  database: "pictureminer-api"
Redis:
  redishost: "localhost"
  Redisport: "6379"
server:
  port: "9000"
  secret: "mySecretKey"
s3:
  AWSRegion: "us-east-1"
  AWSAccessKeyID : "AKIA3AKGGBQK5GD2QPDO"
  AWSSecretAccessKey : "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"
  BucketName : "mined-pictures"
python: 
  microservicehost: "https://yiowpv.deta.dev/api/microservice/content"
