basePath: /api/v1/
definitions:
  model.MinedImage:
    properties:
      dateCreated:
        type: string
      dateModified:
        type: string
      id:
        type: string
      imageKey:
        type: string
      imageName:
        type: string
      imagePath:
        type: string
      textContent:
        type: string
      userID:
        type: string
    type: object
  model.Ping:
    properties:
      email:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      profile_key:
        type: string
      profile_url:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  utility.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        description: for errors that occur even if request is successful
      extra: {}
      message:
        type: string
      name:
        description: name of the error
        type: string
      status:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: A picture mining service API in Go using Gin framework.
  title: Minergram
  version: "1.0"
paths:
<<<<<<< HEAD
  /admin/mined-images:
    get:
      description: this returns the mined images of all users
=======
  /admin/users:
    get:
      description: List all users
>>>>>>> fd55bf3a6a78a333fafa32cd3a84e43150f39400
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
<<<<<<< HEAD
              $ref: '#/definitions/model.MinedImage'
            type: array
      summary: this returns the mined images of all users
      tags:
      - Mined Images
=======
              $ref: '#/definitions/model.User'
            type: array
      summary: List all users
      tags:
      - users
>>>>>>> fd55bf3a6a78a333fafa32cd3a84e43150f39400
  /api/v1/health:
    get:
      description: Responds with the server status as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utility.Response'
      summary: Checks the status of the server
      tags:
      - health
    post:
      description: Send a dummy post request to test the status of the server
      parameters:
      - description: Ping JSON
        in: body
        name: ping
        required: true
        schema:
          $ref: '#/definitions/model.Ping'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utility.Response'
      summary: Checks the status of the server
      tags:
      - health
schemes:
- http
swagger: "2.0"
